name: Deploy Legacy App Service to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_APP_SERVICE_NAME: 'myLegacyAppService' 
  AZURE_APP_SERVICE_PACKAGE_PATH: './legacy-app-service'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v4
     
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_APP_SERVICE_NAME }}
        package: '${{ env.AZURE_APP_SERVICE_PACKAGE_PATH }}'
